version: '3'
services:
    nginx-proxy:
        image: bitnami/nginx:1.25.3
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /opt/services/conf/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
            - /opt/services/certs:/etc/nginx/certs
            - /opt/services/nginx-logs:/opt/bitnami/nginx/logs
        user: "root:root"
        restart: unless-stopped
        networks:
            - services_net

    postgresql:
        image: postgres:alpine3.18
        container_name: postgresql
        restart: unless-stopped
        networks:
            - services_net
        volumes:
            - /opt/services/db-data:/var/lib/postgresql/data
        environment:
            - 'POSTGRES_DB=gogs'
            - 'POSTGRES_USER=gogs'
            - 'POSTGRES_PASSWORD='
        logging:
            driver: "json-file"
            options:
                max-size: "500k"
                max-file: "50"

    gogs:
        image: gogs/gogs:latest
        container_name: gogs
        restart: unless-stopped
        ports:
            - "7999:22"
        environment:
            - "VIRTUAL_HOST=xxx.xxx.com"  #This will be the domain name through which you will access gogs.
            - "VIRTUAL_PORT=3000"
        networks:
            - services_net
        volumes:
            - "/opt/services/gogs-data:/data"
            - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
        depends_on:
            - postgresql

networks:
    services_net:
        driver: bridge
